# syntax=docker/dockerfile:1

# ---- Base image -------------------------------------------------------
# Alpine keeps the image small; pin to the Node major version this project
# was developed against to avoid surprise breakages.
FROM node:20-alpine AS base

# ---- Dependencies stage ------------------------------------------------
# Installing deps in their own stage lets Docker cache this layer as long
# as package.json doesn't change, even if source files change often.
FROM base AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# ---- Build stage --------------------------------------------------------
# Compiles the Next.js app using the dependencies installed above.
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED=1

# BUILD_STANDALONE switches next.config.mjs from the default static export
# (used for the Cloudflare Pages deploy) to a standalone Node server.
ENV BUILD_STANDALONE=1
RUN npm run build

# ---- Runtime stage --------------------------------------------------------
# Final image only contains the standalone server output (see
# `output: "standalone"` in next.config.mjs), keeping it lean and free of
# devDependencies / build tooling.
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Run as a non-root user for better container security.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Static assets and public files must be copied in manually because the
# standalone output does not include them by default.
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is generated by the standalone output (next build with
# output: "standalone") — it's a self-contained Node server, no `next start` needed.
CMD ["node", "server.js"]
